version: '3.4'

services:
  tigmitnekoboard:
    image: tigmitnekoboard
    build:
      context: .
      dockerfile: ./Dockerfile

      privileged: true
      tty: true
      volumes:
        - /dev/bus/usb:/dev/bus/usb
